### ISSUE TITLE
Authentication error.

### ISSUE THREAD

**Issue by lcharles123** [fkalis/bash-onedrive-upload#10]
Hello!
Appears this, after enter with the autenticated url on terminal:

Something went wrong, here is the API response:
{"error":"server_error"}

I have downloaded master.zip and put bash-json-parser manualy inside libs. What could be wrong?

Thank you!

**Comment by fkalis** [comment]
It seems like you have entered the complete url after authenticating.

When the url is `https://login.live.com/oauth20_desktop.srf?code=Md81f7079-1000-1aef-ef28-9e4d00fff7b4&lc=1031`, you have to enter _only_ `Md81f7079-1000-1aef-ef28-9e4d00fff7b4`.

If this was the problem, I'll take it as a hint to optimize this part of the authentication process.

**Comment by lcharles123** [comment]
Yes, works now! Many Thanks!
