### ISSUE TITLE
Specifying different remote filename

### ISSUE THREAD

**Issue by Guntiss** [fkalis/bash-onedrive-upload#11]
Using
./onedrive-upload -f "remotedir/remote filename.txt" localtemp.txt

Uploads file localtemp.txt to folder
 "remotedir/remote filename.txt/localtemp.txt"

Any workarounds to specify remote filename without renaming local?

**Comment by fkalis** [comment]
This is not yet possible.

If the script would allow the usage `./onedrive-upload -f "remotedir/remote filename.txt" localtemp.txt`, what do you expect to happen, if you specify two local files: `./onedrive-upload -f "remotedir/remote filename.txt" localtemp1.txt localtemp2.txt`

Do you have any suggestions how the syntax could look like?

**Comment by Guntiss** [comment]
Well you're right. I am migrating from Dropbox Uploader script which supported such feature, so I am stuck with this issue. Any way to quickly modify this script to take second parameter as a remote filename? Since I am uploading only one file at a time. I don't have such bash skills unfortunately.

**Comment by fkalis** [comment]
I think this could be a useful feature, so I will see if I find an appropriate usage syntax to make this possible.

Maybe something like `./onedrive-upload file.txt --as renamedfile.txt` as this is still compatible with multi file upload. Although I'm not sure what one would expect to happen for `./onedrive-upload file*.txt --as renamedfile.txt`.

**Comment by Guntiss** [comment]
Maybe just prevent uploading multiple files if --as argument is provided.

**Comment by fkalis** [comment]
You can now upload your files with a different remote name

> ./onedrive-upload -f "remotedir/remote" -r localtemp.txt filename.txt

**Comment by Guntiss** [comment]
This looks great! Just right after I spent few hours trying to fix It myself :D
Thanks!
