### ISSUE TITLE
Cannot upload to shared folder

### ISSUE THREAD

**Issue by danielskowronski** [fkalis/bash-onedrive-upload#16]
When I try to upload file to shared folder (to which I have read-write access) I get one of those errors:
- if folder ID (sometething like 1234567890ABCDEF!1234) is provided in config: "An error has occurred while uploading 'test.txt' (Code: 403)"
- if path is provided via -f flag (folder is attached to my onedrive - it's visible as regular folder in root directory and can be synced with pc): "An error has occurred while uploading 'test.txt' (Code: 501)

Debug info below:
<pre>
$ ~/bash-onedrive-upload/onedrive-upload -d -f "SFI" test.txt
2016-01-28 11:08:26 Acquiring new access token
2016-01-28 11:08:27 Searching for 'SFI' in root
2016-01-28 11:08:28 api_folder_id is now 'BBF1234567890ABC!304827'
2016-01-28 11:08:28 Size of test.txt is less than or equal to 104857600 bytes, will use simple upload
2016-01-28 11:08:28 Acquiring new access token
2016-01-28 11:08:29 Uploading 'test.txt' as 'test.txt' into BBF1234567890ABC%21304827
An error has occurred while uploading 'test.txt' (Code: 501)

$ nano ~/bash-onedrive-upload/onedrive.cfg
$ ~/bash-onedrive-upload/onedrive-upload -d test.txt #with folder ID in cfg
2016-01-28 11:09:21 Size of test.txt is less than or equal to 104857600 bytes, will use simple upload
2016-01-28 11:09:21 Acquiring new access token
2016-01-28 11:09:22 Uploading 'test.txt' as 'test.txt' into 1234567890ABCDEF%212217
An error has occurred while uploading 'test.txt' (Code: 403)
</pre>

**Comment by fkalis** [comment]
I did some research, but unfortunately this is [not possible](https://msdn.microsoft.com/en-us/library/office/dn659731.aspx#get_a_list_of_onedrive_objects_that_are_shared_with_the_signed_in_user).

> Creating, updating, or deleting files in a folder that is shared with the signed-in user is not supported by the OneDrive API. Apps can manipulate only files that are owned by the signed-in user.
> We don't support third-party apps that upload files to shared folders.

**Comment by danielskowronski** [comment]
I also did some research and found that MS released completly new API - https://dev.onedrive.com/
But I beleive that implementing it in existing app isn't trivial.

**Comment by fkalis** [comment]
You are right, the new API seems to support this.

I will take a look at https://dev.onedrive.com/misc/working-with-links.htm and see if I can make it work.

**Comment by fkalis** [comment]
I did not change anything, but it seems like the current version of the API finally supports uploading into shared folders the same way as uploading into own folders works.

I have successfully uploaded a file into a shared folder. I tried both ways: Specifying the folder id in the `onedrive.cfg` and providing the path via the `-f` option.

Can you please try again if uploading works for you?

**Comment by danielskowronski** [comment]
I did have to rauthorize app.
For me it works when path ID is provided in config. But it does not work is those situations:
- when I try to upload to user readable path witdh depth=1 ("shared_folder/") - response is 501
- when I try to upload to user readable path deeper than one subdir it says "Proxying for sync ghost items is not implemented."

But anyway - it works, thanks :)

**Comment by danielskowronski** [comment]
But when shared folder ID is specified in cfg file relative paths in -f parameter works like a charm

**Comment by fkalis** [comment]
For me it works in the following situations:

* `api_root_folder="root"` combined with `-f "path/to/shared/folder"
* `api_root_folder="items/SHARED_FOLDER_ID"` without any additional parameter
* `api_root_folder="items/SHARED_FOLDER_ID"` combined with `-f "arbitrary/path/within/shared/folder"

Of course I have write access to that shared folder.

I will consider this issue as resolved. If you encounter other problems, feel free to open a new one.
