### ISSUE TITLE
Illegal xargs error shown in Mac OS X

### ISSUE THREAD

**Issue by huming2207** [fkalis/bash-onedrive-upload#17]
Hi,

Firstly, thanks for your script, which helps me a lot!
But I've got an issue when I run it under OSX, it shown me like this:
```
JacksonHuMac:bash-onedrive-upload Jackson$ ./onedrive-upload -d -f "temporary" /Volumes/Hu/Photos/2015/xyz/*
2016-01-02 17:21:29 Acquiring new access token
2016-01-02 17:21:39 Searching for 'temporary' in root
2016-01-02 17:21:48 api_folder_id is now 'B*************6!5****5'
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

But when I ran the script with the same path and same files under Debian Linux in my virtual machine, it works pretty fine. Also I checked about some articles and someone said the **xargs** in OSX is not exactly the same as the one in Linux. Maybe that should be the problem, but I don't know how to fix it.

See: http://www.linuxforums.org/forum/newbie/193120-linux-command-macosx-options-xargs.html

Anyway, thanks and happy new year!

Regards,
Jackson

**Comment by fkalis** [comment]
It looks like *xargs* in OSX supports only the short parameter name for `--max-procs`. Luckily *xargs* in Linux supports both parameter versions.

**Comment by huhu2207** [comment]
Yep, thanks for your update, I will check it later.

**Comment by huming2207** [comment]
@fkalis Hi, I've found there is still a bug there, which it shown me like this:

```
./onedrive-upload -f "xyz" -d /Volumes/Untitled/OneDrive/xyz/Backup.MOV
2016-01-04 09:29:20 Acquiring new access token
2016-01-04 09:29:21 Searching for 'xyz' in root
2016-01-04 09:29:23 Creating folder 'xyz' in ''
2016-01-04 09:29:25 api_folder_id is now 'B*************!5*******'
du: illegal option -- b
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]
./onedrive-base: line 407: [: -gt: unary operator expected
2016-01-04 09:29:25 Size of Backup.MOV is less than or equal to 104857600 bytes, will use simple upload
2016-01-04 09:29:25 Acquiring new access token
2016-01-04 09:29:26 Uploading '/Volumes/Untitled/OneDrive/xyz/Backup.MOV' as 'Backup.MOV' into B****************16%21*****7
An error has occurred while uploading '/Volumes/Untitled/OneDrive/xyz/Backup.MOV' (Code: 413)
```

I checked about this, it seems that some of the UNIX systems such as Apple Mac OSX does not support **"du -b"**, you may need to change it to **"du -B"** instead.

This issue article may helps: https://github.com/lrsjng/h5ai/issues/154

Regards,
Jackson

**Comment by huming2207** [comment]
@fkalis  BTW, the MOV file I mentioned above is nearly 900MB, so it shouldn't use the "simple upload" due to the limitation of M$'s OneDrive API.

**Comment by huming2207** [comment]
Also I've tested on Debian and MinGW Msys in Windows, it works fine for transmitting huge video files.

**Comment by fkalis** [comment]
The simple upload was chosen because du was unable to determine the filesize.

I will have a look at Macs implementation of du tomorrow.

**Comment by huming2207** [comment]
Okay thanks. Also sorry for that I don't know much about bash script.

**Comment by huming2207** [comment]
Hi @fkalis ,

I've just set a pull request with my patch. I use "stat -f%z" instead of "du -b" when it detects the user's OS is Mac OSX.

Regards,
Jackson
