### ISSUE TITLE
ability to work with scope onedrive.appfolder

### ISSUE THREAD

**Issue by benjaminNZ** [fkalis/bash-onedrive-upload#21]
I created the permissions but couldnt seem to get the /drive/special/approot to work.. Guessing more api changes?

Be handy for permissions to only allow the upload script access to its own folder.

**Comment by benjaminNZ** [comment]
I added the scope onedrive.appfolder to the authorization and removed the normal readwrite 

I had no "apps" folder so i created one to try create the Apps\appnamehere but using that didnt work..
https://dev.onedrive.com/misc/appfolder.htm
https://dev.onedrive.com/items/special_folders.htm

It says it will make the folder upon writing to it..

**Comment by fkalis** [comment]
Did you checkout the latest version of the script and follow [the instructions from the README file](https://github.com/fkalis/bash-onedrive-upload#less-permissions-for-uploads)?

You need to remove all permissions for your app ([Link](https://account.live.com/consent/Manage)) and reauthorize using the latest version of the script.

You also need to change 

    export api_permissions="onedrive.readwrite"
to

    export api_permissions="onedrive.approot"

and

    export api_root_folder="items/123419ACDA5678AB!45321"

to

    export api_root_folder="special/approot"

**Comment by benjaminNZ** [comment]
Hi, Sorry im a github noob. Saw the 'notes' which were actually your commits.

Just tried and tested. Thanks for getting onto this so quickly! Handy to use up some of that space for some backups.

**Comment by benjaminNZ** [comment]
OK had an issue with largefiles and adding --tlvs1 to the curl_opts seems to fix the random SSL error i got halfway through it uploading.

**Comment by fkalis** [comment]
I hope I'm not misunderstanding your answer, but it reads as if the issue is fixed for you and the approot setting works as expected.
