### ISSUE TITLE
Refresh token not found

### ISSUE THREAD

**Issue by diman82** [fkalis/bash-onedrive-upload#26]
I get the token, but with a wierd "Something went wrong" error message, and I can't upload anything.

When ready, please enter the value of the code parameter (from the URL of the blank page) and press return
M32509d39-2b15-6e4b-7d7c-c493dac159dc
./onedrive-authorize: line 14: ./libs/json/bash-json-parser: No such file or directory
Something went wrong, here is the API response:
{"token_type":"bearer","expires_in":3600,"scope":"wl.offline_access onedrive.readwrite","access_token":"EwB4Aq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAY8QGX37jfSADQfgzfYClEbWQLpK7zLHBqBCeaAKoapnP4uDzrwVDxb8Xxsh3ky8WFU/RowP+Haq2oEKXzUeFkdLxCFCfGRvh8JADs+lvWDBLPndzRMu8u2hL2hq2Cv/udyqST00CCys2q+SontZW01FBnozHizHhi6a4X8WeteSsV1zA7TTj7P++yKnPjfKxeWYKHPVdkLjQG/aBhio7TZFDLPIzoAJlbd6UI/rFEoDpRo2Dbi1ObJhC1i73zBmHbUK53qEoEDYdSZUhdCEKdPMVxsArpnPIvhuTutb+jLQUYmF89L5m0qfN/dpmW726b0PWMJshxLXRWpWnUYHWRkDZgAACGkNzZgCkIHMSAH86ul90th7y3KwDSyGk7TaNrs2KfODPylhhK/8Goue973diSNp5TGaQNM332oP/GXjCjj1bVLhUcd1jcsqxRiYuskM/HsjF3iF9Q1fIhaNST+XaVfI/fx3+VPP1T5boJ2Jxw0wAlBeFvhLhgpoFIA0gRpVZfNT1L1o1/oau+lVtI4xvejGrmDr40tLRyBVKCP1MGZ2NwfTFYIGTb1YOpllu/tMWP9kP+x4WMSZgqL6nK5hCFS5A8Jf9x1tLbJC4ha8DafiB/KrNnSsa55Sm+oT9F+dUjgcr3QQpdtRvWUOhift5dw5sM73Sfm8PjrvYVt+UdqkCN7H1wNlp5L8WTdK8pK/msQiTRP8qvSqqpJPPiYx9hBOm61BelXTNXo2sR+ZOlgI0hWzaifzrsPFMauaZ8GXu06W7ZtE1J9CWHIm5l6CM2u4DBysbgE=","refresh_token":"MCc943ClnqoydWS5*w!NAMvGPjbvadYFh*Ji2UEVdtXPj0IL*nhsvY74KU7MVZ6BE3lW2oxR9kEV8iXDS4z467Raqo1TdcYZlFp9DA8v4zVNALVww5lOW3vmRZP3daZ5CpgqblmDrVucPsyqDw2jcvO05UrKN2A8R9rdmpyfuC5bth9NIzMQREh!6b4MqjoGYXxrfKEXS438Ng7GgJ1g1ZhqNMHxx5*3TXWsZ7LfxzMrkwrxKtG37DkI7EWjLmWZy93zvmE0MDe8D7A!HcHe01X73E6Ssiz53slfCdK*JtXSRmSRu*8IGJ9gm5XvXGJP6qIJsyd72FgMPi7r!bICYvMRQpqNHpJLShN0loRYQnkCX","user_id":"b570e8ef044b76bf8fd038fdb3cfdafe"}

Diman82@Givataim-PC /cygdrive/c/cygwin64/bash-onedrive-upload-master
$ ./onedrive-
onedrive-authorize  onedrive-base       onedrive-upload

Diman82@Givataim-PC /cygdrive/c/cygwin64/bash-onedrive-upload-master
$ ./onedrive-upload rsload.net.TeamViewer.7z
Refresh token not found, please complete the authorization process first
Refresh token not found, please complete the authorization process first
Refresh token not found, please complete the authorization process first
An error has occurred while uploading 'rsload.net.TeamViewer.7z' (Code: )

**Comment by fkalis** [comment]
The relevant line of your error message is

    ./onedrive-authorize: line 14: ./libs/json/bash-json-parser: No such file or directory

It looks as if you didn't checkout the submodule (`git clone --recursive`). You can checkout the submodule by executing the following commands.

    $ git submodule init
    $ git submodule update

**Comment by diman82** [comment]
Yep, my bad, now works.
