### ISSUE TITLE
Onedrive for Business support

### ISSUE THREAD

**Issue by alexlehm** [fkalis/bash-onedrive-upload#27]
The authorize process currently supports onedrive personal only, would this work with onedrive for business as well?

**Comment by fkalis** [comment]
I don't know. Maybe if you replace the URLs used for OneDrive Personal with the URLs described [here](https://dev.onedrive.com/auth/aad_oauth.htm#register-your-app-with-azure-active-directory).

I don't have an OneDrive Business Account, so I cannot test this.

**Comment by alexlehm** [comment]
Thanks for the page, it turns out, admin privileges are required to create apps, so I cannot test it as a normal office for business user.

**Comment by fkalis** [comment]
rootik has provided [support for OneDrive for Business](https://github.com/fkalis/bash-onedrive-upload/pull/29).
