### ISSUE TITLE
Can you add a funcation?

### ISSUE THREAD

**Issue by 0oVicero0** [fkalis/bash-onedrive-upload#36]
Cloud you add a funcation to list file name for 'OneDrive for Business'?
Thanks!

**Comment by rootik** [comment]
I have some progress. This is test run:
`# ./onedriveb-ls
total 3 items
xxx yyy zzz           0      2016-08-23T05:51:41Z    Backup
xxx yyy zzz           0      2016-08-15T10:45:55Z    Protected
xxx yyy zzz      422340      2016-08-09T11:15:25Z    Office 365 Customer Security Considerations Preview.xlsx
`

**Comment by 0oVicero0** [comment]
Yes, This is what I want.
Thanks~
Where I can find it ?

**Comment by rootik** [comment]
@0oVicero0 finally you can test it.
The script not production yet, so you need [download](https://github.com/rootik/bash-onedrive-upload/tree/staging) it from my staging branch.
Here is sample output.
Folder contents:
```
./onedriveb-ls Protected/Test
Protected/Test folder contents
2016-11-02 10:50  d                0    Test1
2016-11-02 10:49  d                1    Test2
2016-11-02 10:50                  12    file1.txt
        total number of items 3
        total 12 bytes in 1 file(s)

```
And particular file details with the anonymous download link:
```
./onedriveb-ls /Protected/Test/Test2/file.txt
2016-11-02 10:49                  10    file.txt        https://isdukraine-my.sharepoint.com/personal/rootik_staging_com/_layouts/15/download.aspx?guestaccesstoken=ZIOTPVeUYiVHDgvKEb8cMnn32c8As0XGbfm3KSrAe5A%3d&docid=1fee4507b518c42a4acd49e3dd3d25626&expiration=2016-11-02T15%3a12%3a37.000Z&userid=3&authurl=True&NeverAuth=True
```

**Comment by 0oVicero0** [comment]
There is a problem : 
List some files name showed unicode.

How to fix it?

**Comment by rootik** [comment]
This was expected :) I have implemented unicode characters support.
You can download modified `onedriveb-base` and `onedriveb-ls` files from my [staging branch](https://github.com/rootik/bash-onedrive-upload/tree/staging) and test.
Thanx for testing it!

**Comment by rootik** [comment]
Last item name in unicode:
```
./onedriveb-ls /Protected/Test
/Protected/Test folder contents
2016-11-02 10:50  d                0    Test1
2016-11-02 10:49  d                1    Test2
2016-11-02 10:50                  12    file1.txt
2016-11-02 21:53                   0    тест.txt
        total number of items 4
        total 12 bytes in 2 file(s)

```

**Comment by 0oVicero0** [comment]
fixed it!
It works well !!!
Thanks fix it~

**Comment by rootik** [comment]
Some news: better unicode characters support in the new [commit](https://github.com/rootik/bash-onedrive-upload/tree/staging).

**Comment by 0oVicero0** [comment]
Very good!
It's OK~
