### ISSUE TITLE
Public clients can't send a client secret

### ISSUE THREAD

**Issue by Wsget** [fkalis/bash-onedrive-upload#41]
I can view the following message.

![access](https://cloud.githubusercontent.com/assets/5674610/21463859/1266112a-c9b3-11e6-90ef-6f7070f9bbde.png)

But,  After that

When ready, please enter the value of the code parameter (from the URL of the blank page) and press return

And I input below parameter

code=M7c53xxx7-x4xf-2867-3931-e0000000f0&lc=0000

and

Something went wrong, here is the API response:
{"error":"invalid_request","error_description":"Public clients can't send a client secret."}

Plus

App ID has always dash. So readme file need to update.

thx.

**Comment by weismat** [comment]
Same problem here I think.
I am trying to use the URL from ./onedrive-authorize and I am failing with a similar error response.
Please advise!

**Comment by weismat** [comment]
Same issue here...
Also removing the data of the & does not make a difference.

> ./onedrive-authorize: line 14: ./libs/json/bash-json-parser: No such file or directory
Something went wrong, here is the API response:
{"error":"invalid_request","error_description":"Public clients can't send a client secret."}

**Comment by fkalis** [comment]
@Wsget: You must only enter the `M7c53xxx7-x4xf-2867-3931-e0000000f0` part. If you did, we have to take a look at your registered apps settings.

@weismat: It seems like you are missing the submodule `bash-json-parser`. Did you checkout the repository with the `--recursive` parameter as stated in the Readme file?

**Comment by weismat** [comment]
I copied the zip directory and the file was not included. I created in now manually and it is good to go. I am stuck now though at uploading files and always receive "Folder structure created, no files uploaded."

**Comment by MatthiasWeiser** [comment]
weismat with my company login.
./onedrive-upload -r onedrive-upload test
No refresh token received from API. Please try again or re-authorize.
No refresh token received from API. Please try again or re-authorize.
No refresh token received from API. Please try again or re-authorize.
An error has occurred while uploading 'onedrive-upload' (Code: )

**Comment by Wsget** [comment]
# ./onedrive-authorize
Please open the following URL in your browser and follow the steps until you see a blank page:
https://login.live.com/oauth20_authorize.srf?client_id=1xxx0000-000x-0000-0000-0xxx000xx00x&scope=wl.offline_access%20onedrive.readwrite&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

When ready, please enter the value of the code parameter (from the URL of the blank page) and press return
xx00xxx00-000x-00xx-x000-000000x00x00
Something went wrong, here is the API response:
{"error":"invalid_request","error_description":"Public clients can't send a client secret."}



And my apps settings

# Authentication config
export api_client_id="0xxx0000-000x-0000-0000-0xxx000xx00x"
export api_client_secret="00XX0X00X000X0X0000X000000X000X000X0XX00"


api_client_secret is Application Secrets - Private Key. Is that right?

and api_client_id is Application Id. Is that right?

**Comment by fkalis** [comment]
> App ID has always dash. So readme file need to update.

If your App ID contains dashes, you have created the wrong (unsupported) application type. Please take a look at [this comment](https://github.com/fkalis/bash-onedrive-upload/pull/40#issuecomment-269543611).

**Comment by Wsget** [comment]
When I go into this link

https://apps.dev.microsoft.com/#/appList

![00_link](https://cloud.githubusercontent.com/assets/5674610/21534494/45b099e6-cdab-11e6-9ec5-5228b5d23832.png)

and click add an app

![01_add](https://cloud.githubusercontent.com/assets/5674610/21534499/56674906-cdab-11e6-96d4-a68cbfd04324.png)

and after create application

![02_view](https://cloud.githubusercontent.com/assets/5674610/21534500/6a285f66-cdab-11e6-8046-80cd88b38c3a.png)

An ID with a dash is created.

There is no  "create your application in the Live SDK applications section" option.

I mean there is no other option.

So, take a look at this problem plz.

**Comment by fkalis** [comment]
Please use the link from the README file and try again: https://apps.dev.microsoft.com/#/appList/create/sapi

This should automatically ask for an application name without clicking `Add an app`.

**Comment by Wsget** [comment]
Ok. I got it.

But when I upload file, always receive

"Folder structure created, no files uploaded"

message.

**Comment by fkalis** [comment]
Bug found and fixed.

**Comment by weismat** [comment]
Thank you very much for your quick help and support.

**Comment by WSGVET** [comment]
Thx so much.

I  will try.!

**Comment by Wsget** [comment]
It works great!
