### ISSUE TITLE
Error while authorizing/granting permissions with personal account

### ISSUE THREAD

**Issue by mecp** [fkalis/bash-onedrive-upload#44]
This is the error message I got while granting permissions to the app by going to url mentioned in terminal message after running the `onedrive-authorize` script.

```json
Something went wrong, here is the API response:
{
   "error":"invalid_request",
   "error_description":"Public clients can't send a client secret."
}
```
**FIX**:
Removing the `client_secret=${api_client_secret}` from url fixes it.

**Comment by fkalis** [comment]
Please take a look a #41 and follow the instructions.
