### ISSUE TITLE
Allow upload of files larger than 100MB

### ISSUE THREAD

**Issue by fkalis** [fkalis/bash-onedrive-upload#6]
Implement http://onedrive.github.io/items/upload_large_files.htm

**Comment by fkalis** [comment]
It is not yet possible to upload files directly into the root folder.

**Comment by matteocontrini** [comment]
Sorry, is this supposed to work?

**Comment by fkalis** [comment]
You can checkout the feature branch for large files. It should work, but I haven't tested it enough to merge it back in the master.

**Comment by matteocontrini** [comment]
Ah it's in the branch, I didn't notice that

**Comment by matteocontrini** [comment]
It works, thanks!
With a connection faster than 20 Mbps, a chunk is uploaded in less than a second, and then it seems that it takes something like 10 seconds to start uploading the next part. Is it ok to increase the chunk size in these cases?

**Comment by fkalis** [comment]
According to the [official documentation](https://dev.onedrive.com/items/upload_large_files.htm), you can choose a chunk size of up to 60 MiB.

> You can either upload the entire file in one fragment up to 60 MiB (60 * 1024 * 1024 bytes)
